[package]
name = "sce"
version = "0.1.0"
authors = ["Avi Srivastava <avi.srivastava@nyu.edu>", "Rob Patro <rob@cs.umd.edu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num = "0.3.0"
csv = "1.1.3"
sprs = { git = "https://github.com/k3yavi/sprs" } #"0.8.0"
flate2 = "1.0.16"
libmath = "0.2.1"
byteorder = "1.3.4"
num-traits = "0.2.12"
