[package]
name = "single"
version = "0.1.0"
authors = ["Avi Srivastava <avi.srivastava@nyu.edu>", "Mike Love", "Rob Patro <rob@cs.umd.edu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sprs = "0.8.0"